// frontend/src/views/Login.vue
<template>
  <div class="login-container">
    <el-card class="login-box">
      <h2 class="title">智慧餐饮系统</h2>
      <el-form :model="loginForm" :rules="rules" ref="loginFormRef" @keyup.enter="handleLogin">
        <!-- 角色选择 -->
        <el-form-item prop="role">
          <el-select v-model="loginForm.role" placeholder="请选择角色" class="full-width">
            <el-option v-for="role in roleOptions" :key="role.value" :label="role.label" :value="role.value" />
          </el-select>
        </el-form-item>

        <!-- 用户名 -->
        <el-form-item prop="username">
          <el-input v-model="loginForm.username" placeholder="请输入账号" prefix-icon="User" />
        </el-form-item>

        <!-- 密码 -->
        <el-form-item prop="password">
          <el-input v-model="loginForm.password" type="password" placeholder="请输入密码" prefix-icon="Lock" show-password />
        </el-form-item>

        <!-- 图形验证码 -->
        <el-form-item prop="captcha">
          <div class="captcha-wrapper">
            <el-input v-model="loginForm.captcha" placeholder="请输入验证码" class="captcha-input" />
            <img :src="captchaImage" class="captcha-image" @click="refreshCaptcha" />
          </div>
        </el-form-item>

        <!-- 登录按钮 -->
        <el-form-item>
          <el-button type="primary" class="full-width" :loading="loading" @click="handleLogin">
            登录
          </el-button>
        </el-form-item>
      </el-form>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue';
import { useRouter } from 'vue-router';
import { ElMessage } from 'element-plus';
import type { FormInstance, FormRules } from 'element-plus';
import { loginAPI, getCaptchaAPI } from '@/api/auth';

import { useStore } from 'vuex'
const router = useRouter();
const store = useStore();

// 表单数据
const loginForm = reactive({
  role: '',
  username: '',
  password: '',
  captcha: ''
});

// 角色选项（示例数据）
const roleOptions = [
  { label: '管理员', value: 'admin' },
  { label: '收银员', value: 'cashier' },
  { label: '财务', value: 'finance' },
  { label: '营销', value: 'marketing' }
];

// 表单验证规则
const rules = reactive<FormRules>({
  role: [{ required: true, message: '请选择角色', trigger: 'change' }],
  username: [{ required: true, message: '请输入账号', trigger: 'blur' }],
  password: [{ required: true, message: '请输入密码', trigger: 'blur' }],
  captcha: [{ required: true, message: '请输入验证码', trigger: 'blur' }]
});

// 验证码处理
const captchaImage = ref('');
const refreshCaptcha = async () => {
  const res = await getCaptchaAPI();
  captchaImage.value = res.data.image;
};

// 登录逻辑
const loginFormRef = ref<FormInstance>();
const loading = ref(false);
const handleLogin = async () => {
  // 表单验证
  await loginFormRef.value?.validate();
  loading.value = true;

  try {
    // 调用登录接口
    const res = await loginAPI({
      ...loginForm,
      password: encryptPassword(loginForm.password) // 密码加密
    });

    // 存储Token和用户信息
    store.commit('SET_TOKEN', res.data.token);
    store.commit('SET_USER_INFO', res.data.user);

    // 跳转到主页
    router.push('/');
    ElMessage.success('登录成功');
  } catch (error) {
    refreshCaptcha(); // 刷新验证码
    ElMessage.error('登录失败，请检查输入');
  } finally {
    loading.value = false;
  }
};

// 密码加密函数
const encryptPassword = (password: string) => {
  // 实际使用CryptoJS加密（此处为示例）
  return btoa(password);
};

// 初始化验证码
refreshCaptcha();
</script>

<style scoped>
.login-container {
  display: flex;
  justify-content: center;
  align-items: center;
  background: #f0f2f5;
}

.login-box {
  width: 400px;
  padding: 24px;
}

.title {
  text-align: center;
  margin-bottom: 24px;
  color: #303133;
}

.full-width {
  width: 100%;
}

.captcha-wrapper {
  display: flex;
  gap: 8px;
}

.captcha-input {
  flex: 1;
}

.captcha-image {
  height: 40px;
  cursor: pointer;
  border: 1px solid #dcdfe6;
  border-radius: 4px;
}
</style>

// frontend/src/pages/auth/Login.tsx
import React, { useState, useEffect } from 'react';
import { Form, Input, Button, Checkbox, Card, message, Space, Image } from 'antd';
import { UserOutlined, LockOutlined, SafetyOutlined } from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import styled from '@emotion/styled';
import * as authApi from '@/api/auth';
import type { LoginParams } from '@/api/auth';

const LoginContainer = styled.div`
  min-height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  background: linear-gradient(120deg, #1677ff 0%, #36cfc9 50%, #0958d9 100%);
  position: relative;
  overflow: hidden;

  &::before {
    content: '';
    position: absolute;
    width: 200%;
    height: 200%;
    background: radial-gradient(circle, rgba(255,255,255,0.1) 0%, rgba(255,255,255,0) 60%);
    top: -50%;
    left: -50%;
    animation: rotate 30s linear infinite;
  }

  @keyframes rotate {
    from {
      transform: rotate(0deg);
    }
    to {
      transform: rotate(360deg);
    }
  }
`;

const LoginCard = styled(Card)`
  width: 100%;
  max-width: 440px;
  border-radius: 16px;
  box-shadow: 0 12px 32px rgba(0, 0, 0, 0.1), 0 2px 6px rgba(0, 0, 0, 0.08);
  backdrop-filter: blur(10px);
  background: rgba(255, 255, 255, 0.95);
  
  .ant-card-head {
    border-bottom: none;
    padding-bottom: 0;
  }
  
  .ant-card-head-title {
    text-align: center;
    font-size: 28px;
    font-weight: 600;
    color: #1677ff;
    padding: 24px 0 12px;
  }

  .ant-card-body {
    padding: 32px;
  }
`;

const StyledForm = styled(Form)`
  .ant-input-affix-wrapper {
    border-radius: 8px;
    height: 46px;
    padding: 8px 16px;
    
    .anticon {
      color: #bfbfbf;
    }
  }

  .ant-input-affix-wrapper-focused,
  .ant-input-affix-wrapper:hover {
    border-color: #1677ff;
    box-shadow: 0 0 0 2px rgba(22, 119, 255, 0.1);
  }

  .login-form-button {
    width: 100%;
    height: 46px;
    border-radius: 8px;
    font-size: 16px;
    margin-top: 8px;
  }
  
  .ant-form-item:last-child {
    margin-bottom: 0;
  }

  .captcha-container {
    display: flex;
    gap: 12px;
    
    .ant-input-affix-wrapper {
      flex: 1;
    }
    
    .captcha-img {
      height: 46px;
      border-radius: 8px;
      cursor: pointer;
      border: 1px solid #d9d9d9;
    }
  }
`;

const SystemTitle = styled.div`
  text-align: center;
  margin-bottom: 32px;
  
  h1 {
    font-size: 28px;
    color: #1677ff;
    margin: 0;
    font-weight: 600;
  }
  
  p {
    color: #666;
    margin: 8px 0 0;
    font-size: 16px;
  }
`;

interface LoginForm extends Omit<LoginParams, 'sessionId'> {
  remember: boolean;
}

const Login: React.FC = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [captchaUrl, setCaptchaUrl] = useState('');
  const [sessionId, setSessionId] = useState('');

  const refreshCaptcha = async () => {
    try {
      const { captchaUrl, sessionId } = await authApi.getCaptcha();
      setCaptchaUrl(captchaUrl);
      setSessionId(sessionId);
    } catch {
      message.error('获取验证码失败，请刷新页面重试');
    }
  };

  useEffect(() => {
    refreshCaptcha();
  }, []);

  const onFinish = async (values: LoginForm) => {
    try {
      setLoading(true);
      const { token, user } = await authApi.login({
        ...values,
        sessionId,
      });

      // 存储认证信息
      localStorage.setItem('token', token);
      localStorage.setItem('userRole', user.role);
      
      message.success('登录成功');

      // 根据角色跳转到对应的子系统
      const roleDefaultPaths: Record<string, string> = {
        admin: '/admin/staff',
        cashier: '/cashier/transaction',
        finance: '/finance/statistics',
        marketing: '/marketing/analysis',
      };

      navigate(roleDefaultPaths[user.role] || '/login');
    } catch (error) {
      refreshCaptcha();
    } finally {
      setLoading(false);
    }
  };

  return (
    <LoginContainer>
      <LoginCard>
        <SystemTitle>
          <h1>智慧餐饮管理系统</h1>
          <p>Smart Restaurant Management System</p>
        </SystemTitle>
        
        <StyledForm
          name="login"
          initialValues={{ remember: true }}
          onFinish={onFinish}
        >
          <Form.Item
            name="username"
            rules={[
              { required: true, message: '请输入用户名' },
              { min: 3, message: '用户名至少3个字符' }
            ]}
          >
            <Input 
              prefix={<UserOutlined />} 
              placeholder="请输入用户名" 
              size="large"
            />
          </Form.Item>

          <Form.Item
            name="password"
            rules={[
              { required: true, message: '请输入密码' },
              { min: 6, message: '密码至少6个字符' }
            ]}
          >
            <Input.Password
              prefix={<LockOutlined />}
              placeholder="请输入密码"
              size="large"
            />
          </Form.Item>

          <Form.Item
            name="captcha"
            rules={[{ required: true, message: '请输入验证码' }]}
          >
            <div className="captcha-container">
              <Input
                prefix={<SafetyOutlined />}
                placeholder="请输入验证码"
                size="large"
              />
              <img
                src={captchaUrl}
                alt="验证码"
                className="captcha-img"
                onClick={refreshCaptcha}
              />
            </div>
          </Form.Item>

          <Form.Item>
            <Space style={{ width: '100%', justifyContent: 'space-between' }}>
              <Form.Item name="remember" valuePropName="checked" noStyle>
                <Checkbox>记住我</Checkbox>
              </Form.Item>
              <a href="/forgot-password" style={{ color: '#1677ff' }}>忘记密码？</a>
            </Space>
          </Form.Item>

          <Form.Item>
            <Button 
              type="primary" 
              htmlType="submit" 
              className="login-form-button"
              loading={loading}
              size="large"
            >
              {loading ? '登录中...' : '登 录'}
            </Button>
          </Form.Item>
        </StyledForm>
      </LoginCard>
    </LoginContainer>
  );
};

export default Login;
